- packages/app/lib/apps/background-sync/BackgroundSync.js
- packages/app/lib/apps/board-api-routes.js
- packages/app/lib/apps/events-sync.js
- packages/app/lib/events.js
- packages/app/lib/index.js
- packages/app/lib/links.js
- packages/app/lib/store.js
- packages/app/package-lock.json
- packages/app/package.json
- packages/app/test/events.test.js
- packages/app/test/links.test.js
- packages/app/test/store.test.js
* Serialize store updates
* Batch apply background synchronized issues
* Allow external parties to hook into background sync
* Allow external parties to hook into updates via update events
> Rework store and background sync

- packages/app/app.yml
- packages/app/lib/apps/checks/Checks.js
- packages/app/lib/apps/checks/index.js
- packages/app/lib/apps/github-app/GithubApp.js
- packages/app/lib/index.js
- packages/app/lib/util/cache.js
- packages/app/package.json
- packages/board/src/Card.scss
- packages/board/src/Card.svelte
- packages/board/src/CardLink.svelte
- packages/board/src/CardStatus.svelte
- packages/board/src/style/variables.scss
> 41 integrate checks

- docs/AUTOMATIC_DEV_FLOW.md
> Create dev flow documentation

- packages/app/app.yml
- packages/app/lib/apps/checks/index.js
- packages/app/lib/apps/events-sync.js
- packages/app/lib/apps/github-app/GithubApp.js
- packages/app/lib/apps/github-checks/GithubChecks.js
- packages/app/lib/apps/github-checks/index.js
- packages/app/lib/apps/github-statuses/GithubStatuses.js
- packages/app/lib/apps/github-statuses/index.js
- packages/app/lib/index.js
- packages/board/src/CardStatus.svelte
> Add status to cards

- packages/app/lib/apps/github-checks/GithubChecks.js
Otherwise funny things happen (exampe: WIP check going crazy).
> Deduplicate checks by name

- docs/STORAGE.md
> docs(project): document storage

- packages/app/lib/apps/dump-store/local/DumpStoreLocal.js
- packages/app/lib/apps/dump-store/s3/DumpStoreS3.js
- packages/app/lib/apps/github-reviews/GithubReviews.js
- packages/app/lib/apps/github-reviews/index.js
- packages/app/lib/apps/reindex-store.js
- packages/app/lib/apps/reviews/index.js
- packages/app/lib/index.js
- packages/app/lib/store.js
- packages/app/wuffle.config.example.js
> Update stored issues on config change

- packages/app/lib/util/links.js
- packages/app/test/util.test.js
Follow-up of #73 to add keywords that waffle previously recognized
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> feat(app): add "connects to" child relationship

- packages/app/lib/apps/background-sync/BackgroundSync.js
Keep track of accessible repositories during background sync
and remove all issues that do not belong to such repositories
immediately.
This prevents issues hanging on the board that are inaccessible
to the board due to ownership transfer or changed GitHub app
permissions.
Closes https://github.com/nikku/wuffle/issues/93
Closes https://github.com/nikku/wuffle/issues/90
> fix(background-sync): properly handle removed repositories

- packages/app/lib/apps/events-sync.js
Closes https://github.com/nikku/wuffle/issues/92
> feat(events-sync): support issue transfer

- packages/app/lib/apps/events-sync.js
Handle <repository.renamed> event and update stored issues accordingly.
> feat(events-sync): support repository renaming

- packages/app/lib/apps/automatic-dev-flow.js
Related to https://github.com/bpmn-io/internal-docs/issues/451
This moves a pull request back to `in progress` once a review requested changes.
@nikku is there any way to unit test those dev flow handlers? Or should I set up a proper local environment? As for now I simply implemented it according to GitHub's API:
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review
* https://docs.github.com/en/graphql/reference/objects#pullrequestreview (+ https://github.com/nikku/wuffle/blob/master/packages/app/lib/apps/github-reviews/GithubReviews.js)
> feat(app/automatic-dev-flow): move on changes requested

- packages/app/lib/util/search.js
- packages/app/test/util.test.js
- packages/board/src/BoardFilter.svelte
Support @today, @last_week and @last_month as relative temporal qualifiers.
> Support relative temporal qualifies via logical names

- packages/app/lib/apps/automatic-dev-flow.js
- packages/app/lib/apps/github-issues/GithubIssues.js
...when creating a numbered branch.
> fix(automatic-dev-flow): no necrobump closed issue

- support/docker/Dockerfile
> chore: use Node@16 to build docker file

- packages/board/src/service-worker.js
> fix: cache only http resources

- docs/SETUP.md
- package-lock.json
- package.json
- packages/app/CHANGELOG.md
- packages/app/lib/columns.js
- packages/app/lib/store.js
- packages/app/package.json
- packages/app/test/store.test.js
- packages/app/wuffle.config.example.js
- packages/board/package.json
Allows to mark columns as _first in, first out_, reversing the default column ordering _last in, first out_. This ensures that new items will be added to the _bottom_ of the column.
Useful, i.e. for review columns, where chronological processing may be desired.
> Allow to sort columns as first in, first out

- packages/app/CHANGELOG.md
- support/docker/Dockerfile
Makes the build more predictable.
> Improve docker building

- package-lock.json
- package.json
- packages/app/CHANGELOG.md
- packages/app/lib/apps/board-routes.js
- packages/app/nodemon.json
- packages/app/package.json
- packages/app/wuffle.config.example.js
- packages/board/package.json
- packages/board/rollup.config.js
- packages/board/src/Api.js
- packages/board/src/BoardFilter.svelte
- packages/board/src/PoweredBy.svelte
- packages/board/src/Taskboard.svelte
- packages/board/src/components/HintList.svelte
- packages/board/src/main.js
- packages/board/src/service-worker.js
Closes https://github.com/nikku/wuffle/issues/190 and various other glitches.
> Prepare v0.62.0

- package-lock.json
- packages/app/CHANGELOG.md
- packages/app/package.json
This allows us to use modern language features :tm: :racing_car:
> Require `node >= 20`

- packages/app/lib/apps/background-sync/BackgroundSync.js
- packages/app/lib/apps/github-app/GithubApp.js
- packages/app/lib/apps/github-checks/GithubChecks.js
- packages/app/lib/apps/github-client/GithubClient.js
- packages/app/lib/apps/github-issues/GithubIssues.js
- packages/app/lib/apps/github-reviews/GithubReviews.js
- packages/app/lib/apps/github-statuses/GithubStatuses.js
- packages/app/lib/apps/security-context/SecurityContext.js
- packages/app/lib/apps/user-access/UserAccess.js
With [probot@14](https://github.com/probot/probot/releases/tag/v14.0.0), we'll need to migrate anyway.
> Ensure we follow modern Probot and Octokit access patterns
